/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ColdClear */

#ifndef _Included_ColdClear
#define _Included_ColdClear
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ColdClear
 * Method:    ccLaunchAsync
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ColdClear_ccLaunchAsync
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ColdClear
 * Method:    ccLaunchWithBoardAsync
 * Signature: (JJJII)J
 */
JNIEXPORT jlong JNICALL Java_ColdClear_ccLaunchWithBoardAsync
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jboolean, jint);

/*
 * Class:     ColdClear
 * Method:    ccDestroyAsync
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_ColdClear_ccDestroyAsync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ColdClear
 * Method:    ccResetAsync
 * Signature: (JJZI)V
 */
JNIEXPORT void JNICALL Java_ColdClear_ccResetAsync
  (JNIEnv *, jobject, jlong, jlong, jboolean, jint);

/*
 * Class:     ColdClear
 * Method:    ccAddNextPieceAsync
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ColdClear_ccAddNextPieceAsync
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ColdClear
 * Method:    ccRequestNextMove
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ColdClear_ccRequestNextMove
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ColdClear
 * Method:    ccPollNextMove
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ColdClear_ccPollNextMove
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ColdClear
 * Method:    ccBlockNextMove
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ColdClear_ccBlockNextMove
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ColdClear
 * Method:    ccDefaultOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ColdClear_ccDefaultOptions
  (JNIEnv *, jobject);

/*
 * Class:     ColdClear
 * Method:    ccDefaultWeights
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ColdClear_ccDefaultWeights
  (JNIEnv *, jobject);

/*
 * Class:     ColdClear
 * Method:    ccFastWeights
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ColdClear_ccFastWeights
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
